[Settings]
ID = "g4m3r-dashboard"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  publish = "build/"
  # This will be your default build command
  command = "yarn build"
  environment = { REACT_APP_API_URL = "https://api.g4m3r.xyz", NODE_ENV = "10.0.0" }

# Production context: All deploys from the Production branch set in your site's deploy settings will inherit these settings.
[context.production]
  environment = { REACT_APP_API_URL = "https://api.g4m3r.xyz", NODE_ENV = "10.0.0" }


# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200